"""empty message

Revision ID: 01578ff9ce2e
Revises: f4521d234063
Create Date: 2023-08-10 13:33:34.621608

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '01578ff9ce2e'
down_revision = 'f4521d234063'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('product',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=50), nullable=True),
    sa.Column('price', sa.Float(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_table('user_product_association',
    sa.Column('user_id', sa.Integer(), nullable=True),
    sa.Column('product_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['product_id'], ['product.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('user_product_association')
    op.drop_table('product')
    # ### end Alembic commands ###
