"""add language to products

Revision ID: 275bf0a94bed
Revises: e2c51de5148a
Create Date: 2023-08-12 11:22:34.557172

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '275bf0a94bed'
down_revision = 'e2c51de5148a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.add_column(sa.Column('language', sa.String(length=5), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('product', schema=None) as batch_op:
        batch_op.drop_column('language')

    # ### end Alembic commands ###
