"""student_id and quantity in Order

Revision ID: 649707a21ff0
Revises: 0a54d47a07c7
Create Date: 2023-08-12 16:19:24.139494

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '649707a21ff0'
down_revision = '0a54d47a07c7'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.add_column(sa.Column('quantity', sa.Integer(), nullable=True))
        batch_op.add_column(sa.Column('student_id', sa.Integer(), nullable=True))
        batch_op.create_foreign_key('student_id', 'user', ['student_id'], ['student_id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('order', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_column('student_id')
        batch_op.drop_column('quantity')

    # ### end Alembic commands ###
